# Generated by Django 4.2 on 2023-04-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=2)),
                ('localizacao', models.CharField(max_length=100)),
                ('denuncias', models.IntegerField(default=0)),
                ('agua', models.IntegerField(default=0)),
                ('medicamento', models.IntegerField(default=0)),
                ('comida', models.IntegerField(default=0)),
                ('municao', models.IntegerField(default=0)),
                ('pontos', models.IntegerField(default=0)),
                ('infectado', models.BooleanField(default=False)),
            ],
        ),
    ]
